module Characters
  def b_by_n
    {
      'a' => {first: '0.', second: '..', third: '..'},
      'b' => {first: '0.', second: '0.', third: '..'},
      'c' => {first: '00', second: '..', third: '..'},
      'd' => {first: '00', second: '.0', third: '..'},
      'e' => {first: '0.', second: '.0', third: '..'},
      'f' => {first: '00', second: '0.', third: '..'},
      'g' => {first: '00', second: '00', third: '..'},
      'h' => {first: '0.', second: '00', third: '..'},
      'i' => {first: '.0', second: '0.', third: '..'},
      'j' => {first: '.0', second: '00', third: '..'},
      'k' => {first: '0.', second: '..', third: '0.'},
      'l' => {first: '0.', second: '0.', third: '0.'},
      'm' => {first: '00', second: '..', third: '0.'},
      'n' => {first: '00', second: '.0', third: '0.'},
      'o' => {first: '0.', second: '.0', third: '0.'},
      'p' => {first: '00', second: '0.', third: '0.'},
      'q' => {first: '00', second: '00', third: '0.'},
      'r' => {first: '0.', second: '00', third: '0.'},
      's' => {first: '.0', second: '0.', third: '0.'},
      't' => {first: '.0', second: '00', third: '0.'},
      'u' => {first: '0.', second: '..', third: '00'},
      'v' => {first: '0.', second: '0.', third: '00'},
      'w' => {first: '.0', second: '00', third: '.0'},
      'x' => {first: '00', second: '..', third: '00'},
      'y' => {first: '00', second: '.0', third: '00'},
      'z' => {first: '0.', second: '.0', third: '00'},
      ' ' => {first: '..', second: '..', third: '..'},
      ',' => {first: '..', second: '0.', third: '..'},
      ';' => {first: '..', second: '0.', third: '0.'},
      ':' => {first: '..', second: '00', third: '..'},
      '.' => {first: '..', second: '00', third: '.0'},
      '!' => {first: '..', second: '00', third: '0.'},
      '?' => {first: '..', second: '0.', third: '00'},
      '*' => {first: '..', second: '.0', third: '0.'},
      '_' => {first: '..', second: '..', third: '00'},
      uppercase: {first: '..', second: '..', third: '.0'}
    }
  end
end